<a href="https://colab.research.google.com/github/allhoesnobros/EXP-9/blob/main/experiment9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment 9
Tools for EDA- Study of Numpy Library
Aayush Vishwakarma
25070123125

In [2]:
#declaraion of numpy
import numpy as np

a=np.array([1,10,20,30,40,50,500])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


In [3]:
print(a.ndim)
print(b.ndim)

1
2


In [4]:
#to check rows and column for matrix
a.shape

(7,)

In [8]:
print(b.shape)


(2, 3)


In [7]:
print(a.dtype)

int64


In [11]:
#in built functions using numpy
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.arange(1,67,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64])

In [21]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [22]:
np.linspace(1,0,5)

array([1.  , 0.75, 0.5 , 0.25, 0.  ])

In [24]:
print(b*2)
print(a+6)

[[ 2  4  6]
 [ 8 10 12]]
[  7  16  26  36  46  56 506]
