<a href="https://colab.research.google.com/github/allhoesnobros/EXP-9/blob/main/experiment9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment 9
Tools for EDA- Study of Numpy Library
Aayush Vishwakarma
25070123125

In [ ]:
#declaraion of numpy
import numpy as np

a=np.array([1,10,20,30,40,50,500])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
#to check rows and column for matrix
a.shape

(7,)

In [ ]:
print(b.shape)


(2, 3)


In [ ]:
print(a.dtype)

int64


In [ ]:
#in built functions using numpy
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(1,67,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64])

In [ ]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
np.linspace(1,0,5)

array([1.  , 0.75, 0.5 , 0.25, 0.  ])

In [ ]:
print(b*2)
print(a+6)

[[ 2  4  6]
 [ 8 10 12]]
[  7  16  26  36  46  56 506]


In [ ]:
import numpy as np

# Define two sample matrices
matrix_a = np.array([[1, 2],
                     [3, 4]])

matrix_b = np.array([[5, 6],
                     [7, 8]])

print("Original Matrix A:\n", matrix_a)
print("Original Matrix B:\n", matrix_b)

# Transpose of Matrix A
transpose_a = matrix_a.T
print("\nTranspose of Matrix A:\n", transpose_a)

# Determinant of Matrix A
determinant_a = np.linalg.det(matrix_a)
print("\nDeterminant of Matrix A:", determinant_a)

# Matrix Multiplication (A @ B)
matrix_product = matrix_a @ matrix_b
print("\nMatrix Multiplication (A @ B):\n", matrix_product)

Original Matrix A:
 [[1 2]
 [3 4]]
Original Matrix B:
 [[5 6]
 [7 8]]

Transpose of Matrix A:
 [[1 3]
 [2 4]]

Determinant of Matrix A: -2.0000000000000004

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]


In [ ]:
print(np.min(a))
print(np.max(a))
print(np.median(a))
print(np.sum(a))

print(np.min(b))
print(np.max(b))
print(np.median(b))
print(np.sum(b))

1
500
30.0
651
1
6
3.5
21


In [ ]:
mat_a = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
mat_b = np.array([[7,8,9],
                [4,5,6],
                 [1,2,3]])
print(mat_a)
print(mat_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
print(mat_a*mat_b)

[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]


In [ ]:
print(mat_a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
print(mat_b.T)

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [2]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9]])

det = np.linalg.det(x)
print("Determinant of x:",det)

transpose = x.T
print("Transpose of x:\n",transpose)

Determinant of x: 0.0
Transpose of x:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
# multiplication of two matrice
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[7,8,9],[4,6,5],[3,2,1]])

product = x @ y

print("product of arrays x and y:\n",product)

product of arrays x and y:
 [[ 24  26  22]
 [ 66  74  67]
 [108 122 112]]
